"""Initial database schema

Revision ID: 174a2a24f639
Revises: 
Create Date: 2025-11-11 23:23:48.156057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174a2a24f639'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_ml_enabled', sa.Boolean(), nullable=False),
    sa.Column('ml_mode', sa.Enum('RECOMMEND', 'AUTO_APPLY', name='mlmodeenum'), nullable=False),
    sa.Column('ml_conf_threshold_priority', sa.Float(), nullable=False),
    sa.Column('ml_conf_threshold_category', sa.Float(), nullable=False),
    sa.Column('agents_can_self_assign', sa.Boolean(), nullable=False),
    sa.Column('agent_visibility_scope', sa.Enum('DEPT', 'ALL', name='visibilityscopeenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'LEAD', 'AGENT', 'USER', name='roleenum'), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'TRIAGE', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='statusenum'), nullable=False),
    sa.Column('priority_manual', sa.Enum('P1', 'P2', 'P3', name='priorityenum'), nullable=False),
    sa.Column('category', sa.Enum('HARDWARE', 'SOFTWARE', 'NETWORK', 'ACCESS', 'OTHER', name='categoryenum'), nullable=True),
    sa.Column('priority_ml_suggested', sa.Enum('P1', 'P2', 'P3', name='priorityenum'), nullable=True),
    sa.Column('priority_ml_confidence', sa.Float(), nullable=True),
    sa.Column('priority_accepted', sa.Boolean(), nullable=True),
    sa.Column('category_ml_suggested', sa.Enum('HARDWARE', 'SOFTWARE', 'NETWORK', 'ACCESS', 'OTHER', name='categoryenum'), nullable=True),
    sa.Column('category_ml_confidence', sa.Float(), nullable=True),
    sa.Column('category_accepted', sa.Boolean(), nullable=True),
    sa.Column('ml_model_version', sa.String(length=50), nullable=True),
    sa.Column('triage_required', sa.Boolean(), nullable=True),
    sa.Column('triage_reason', sa.Enum('LOW_PRIORITY_CONF', 'LOW_CATEGORY_CONF', 'ML_DISABLED', 'MANUAL_FLAG', name='triagereasonenum'), nullable=True),
    sa.Column('self_assign_locked', sa.Boolean(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('labels', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assigned_to_user_id'), 'tickets', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_department_id'), 'tickets', ['department_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_triage_required'), 'tickets', ['triage_required'], unique=False)
    op.create_table('ml_prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('priority_predicted', sa.Enum('P1', 'P2', 'P3', name='priorityenum'), nullable=True),
    sa.Column('priority_confidence', sa.Float(), nullable=True),
    sa.Column('category_predicted', sa.Enum('HARDWARE', 'SOFTWARE', 'NETWORK', 'ACCESS', 'OTHER', name='categoryenum'), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('priority_final', sa.Enum('P1', 'P2', 'P3', name='priorityenum'), nullable=True),
    sa.Column('category_final', sa.Enum('HARDWARE', 'SOFTWARE', 'NETWORK', 'ACCESS', 'OTHER', name='categoryenum'), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prediction_time_ms', sa.Float(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_prediction_logs_created_at'), 'ml_prediction_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_prediction_logs_id'), 'ml_prediction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ml_prediction_logs_ticket_id'), 'ml_prediction_logs', ['ticket_id'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comments_id'), 'ticket_comments', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_ml_prediction_logs_ticket_id'), table_name='ml_prediction_logs')
    op.drop_index(op.f('ix_ml_prediction_logs_id'), table_name='ml_prediction_logs')
    op.drop_index(op.f('ix_ml_prediction_logs_created_at'), table_name='ml_prediction_logs')
    op.drop_table('ml_prediction_logs')
    op.drop_index(op.f('ix_tickets_triage_required'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_department_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to_user_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
