"""add_smart_assignment_fields

Revision ID: 38c6ead62cde
Revises: 40504821516c
Create Date: 2025-11-14 03:31:14.574105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c6ead62cde'
down_revision: Union[str, Sequence[str], None] = '40504821516c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### User table - Smart Assignment fields ###
    op.add_column('users', sa.Column('workload_capacity', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('users', sa.Column('assignment_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('users', sa.Column('availability_status', sa.String(length=20), nullable=False, server_default='AVAILABLE'))

    # ### Ticket table - Assignment Decision Logging ###
    op.add_column('tickets', sa.Column('assignment_method', sa.String(length=50), nullable=True))
    op.add_column('tickets', sa.Column('assignment_confidence', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('assignment_reasoning', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('assignment_alternatives', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'assignment_alternatives')
    op.drop_column('tickets', 'assignment_reasoning')
    op.drop_column('tickets', 'assignment_confidence')
    op.drop_column('tickets', 'assignment_method')

    op.drop_column('users', 'availability_status')
    op.drop_column('users', 'assignment_score')
    op.drop_column('users', 'workload_capacity')
    # ### end Alembic commands ###
