"""add_ensemble_fields_to_ml_logs

Revision ID: 40504821516c
Revises: 5e3187a939ea
Create Date: 2025-11-14 03:20:21.896159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40504821516c'
down_revision: Union[str, Sequence[str], None] = '5e3187a939ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_prediction_logs', sa.Column('ensemble_priority', sa.Enum('P1', 'P2', 'P3', name='priorityenum'), nullable=True))
    op.add_column('ml_prediction_logs', sa.Column('ensemble_confidence', sa.Float(), nullable=True))
    op.add_column('ml_prediction_logs', sa.Column('ensemble_strategy', sa.String(length=50), nullable=True))
    op.add_column('ml_prediction_logs', sa.Column('ensemble_reasoning', sa.Text(), nullable=True))
    # Foreign key constraint не можна додати в SQLite після створення таблиці
    # Relationship працює через SQLAlchemy ORM layer
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'triage_reason',
               existing_type=sa.Enum('LOW_PRIORITY_CONF', 'LOW_CATEGORY_CONF', 'ML_DISABLED', 'MANUAL_FLAG', 'LLM_PRIORITY_MISMATCH', name='triagereasonenum'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.drop_constraint(None, 'ml_prediction_logs', type_='foreignkey')
    op.drop_column('ml_prediction_logs', 'ensemble_reasoning')
    op.drop_column('ml_prediction_logs', 'ensemble_strategy')
    op.drop_column('ml_prediction_logs', 'ensemble_confidence')
    op.drop_column('ml_prediction_logs', 'ensemble_priority')
    # ### end Alembic commands ###
