"""Add ensemble fields to tickets

Revision ID: 431101891901
Revises: 38c6ead62cde
Create Date: 2025-11-14 19:05:22.199398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431101891901'
down_revision: Union[str, Sequence[str], None] = '38c6ead62cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip FK creation for SQLite (not supported)
    # op.create_foreign_key(None, 'ml_prediction_logs', 'users', ['priority_feedback_author_id'], ['id'], ondelete='SET NULL')

    op.add_column('tickets', sa.Column('priority_ensemble', sa.Enum('P1', 'P2', 'P3', name='priorityenum'), nullable=True))
    op.add_column('tickets', sa.Column('ensemble_confidence', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('ensemble_strategy', sa.String(length=50), nullable=True))
    op.add_column('tickets', sa.Column('ensemble_reasoning', sa.Text(), nullable=True))

    # Skip ALTER COLUMN for SQLite (not supported)
    # op.alter_column('tickets', 'triage_reason',
    #            existing_type=sa.VARCHAR(length=17),
    #            type_=sa.Enum('LOW_PRIORITY_CONF', 'LOW_CATEGORY_CONF', 'ML_DISABLED', 'MANUAL_FLAG', 'LLM_PRIORITY_MISMATCH', name='triagereasonenum'),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip ALTER COLUMN for SQLite
    # op.alter_column('tickets', 'triage_reason',
    #            existing_type=sa.Enum('LOW_PRIORITY_CONF', 'LOW_CATEGORY_CONF', 'ML_DISABLED', 'MANUAL_FLAG', 'LLM_PRIORITY_MISMATCH', name='triagereasonenum'),
    #            type_=sa.VARCHAR(length=17),
    #            existing_nullable=True)

    op.drop_column('tickets', 'ensemble_reasoning')
    op.drop_column('tickets', 'ensemble_strategy')
    op.drop_column('tickets', 'ensemble_confidence')
    op.drop_column('tickets', 'priority_ensemble')

    # Skip FK drop for SQLite
    # op.drop_constraint(None, 'ml_prediction_logs', type_='foreignkey')
    # ### end Alembic commands ###
