"""add_ml_model_metadata_and_training_jobs

Revision ID: 5e3187a939ea
Revises: 59d069e7cbe2
Create Date: 2025-11-14 02:59:12.761524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3187a939ea'
down_revision: Union[str, Sequence[str], None] = '59d069e7cbe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision_p1', sa.Float(), nullable=True),
    sa.Column('precision_p2', sa.Float(), nullable=True),
    sa.Column('precision_p3', sa.Float(), nullable=True),
    sa.Column('recall_p1', sa.Float(), nullable=True),
    sa.Column('recall_p2', sa.Float(), nullable=True),
    sa.Column('recall_p3', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('training_samples_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_file_path', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_model_metadata_id'), 'ml_model_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_ml_model_metadata_version'), 'ml_model_metadata', ['version'], unique=True)
    op.create_table('ml_training_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('new_feedback_count', sa.Integer(), nullable=True),
    sa.Column('total_training_samples', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('training_type', sa.String(length=20), nullable=False),
    sa.Column('training_logs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_training_jobs_id'), 'ml_training_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ml_training_jobs_status'), 'ml_training_jobs', ['status'], unique=False)
    # Foreign key constraint не можна додати в SQLite після створення таблиці
    # Relationship працює через SQLAlchemy ORM layer
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_training_jobs_status'), table_name='ml_training_jobs')
    op.drop_index(op.f('ix_ml_training_jobs_id'), table_name='ml_training_jobs')
    op.drop_table('ml_training_jobs')
    op.drop_index(op.f('ix_ml_model_metadata_version'), table_name='ml_model_metadata')
    op.drop_index(op.f('ix_ml_model_metadata_id'), table_name='ml_model_metadata')
    op.drop_table('ml_model_metadata')
    # ### end Alembic commands ###
